guillaume_blog:
    resource: "@GuillaumeBlogBundle/Resources/config/routing.yml"
    prefix:   /

article_platform:
    resource: "@articlePlatformBundle/Resources/config/routing.yml"
    prefix:   /

